/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiTokenClaimSol from "./MultiTokenClaim.sol";
export type { multiTokenClaimSol };
import type * as other from "./other";
export type { other };
