/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MerkleMultipleAirdrop__factory } from "./MerkleMultipleAirdrop__factory";
export { Token__factory } from "./Token__factory";
