/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merkleMultipleAirdropSol from "./MerkleMultipleAirdrop.sol";
export type { merkleMultipleAirdropSol };
import type * as merkleSingleAirdropSol from "./MerkleSingleAirdrop.sol";
export type { merkleSingleAirdropSol };
export type { NFTest } from "./NFTest";
export type { NFTestKalao } from "./NFTestKalao";
export type { USDTest } from "./USDTest";
export type { SNFTest } from "./SNFTest";
